name: banking-storage

services:

  postgres:
    image: postgres:16
    container_name: banking-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: polaris
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../docker/postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d polaris"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - banking-network

  seaweed-master:
    image: chrislusf/seaweedfs:3.91
    container_name: banking-seaweed-master
    command: master

    ports:
      - "9333:9333"

    volumes:
      - ../data/seaweedfs/master:/data

    restart: unless-stopped

    networks:
      - banking-network

  seaweed-volume:
    image: chrislusf/seaweedfs:3.91
    container_name: banking-seaweed-volume

    command: >
      volume
      -mserver=seaweed-master:9333
      -dir=/data
      -port=8080

    depends_on:
      - seaweed-master

    ports:
      - "8080:8080"

    volumes:
      - ../data/seaweedfs/volume:/data

    restart: unless-stopped

    networks:
      - banking-network

volumes:
  postgres-data:

networks:
  banking-network:
    name: banking-network